# Generated by Django 5.0 on 2023-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('contact_details', models.TextField(verbose_name='Contact Details')),
                ('address', models.TextField(verbose_name='Address')),
                ('vendor_code', models.CharField(max_length=20, unique=True, verbose_name='Vendor Code')),
                ('on_time_delivery_rate', models.FloatField(verbose_name='On-Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(verbose_name='Fulfillment Rate')),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
